export const pricingData = {
  locataire: [
    {
      name: "Gratuit",
      price: "0",
      quarterly: "0",
      annual: "0",
      features: {
        properties: "10 propriétés non meublées/mois",
        chat: "Chat simple (5 messages max)",
        contracts: "1 contrat numérique/mois",
        payment: "Paiement sécurisé via Mobile Money",
        advice: "Conseils de base",
        assistance: "Assistance virtuelle KIA (réponses simples)",
        contacts: "Contact avec 2 propriétaires/mois",
      },
    },
    {
      name: "Standard",
      price: "600",
      quarterly: "1 500",
      annual: "5 400",
      features: {
        properties: "Toutes les propriétés (meublées incluses)",
        chat: "Chat avancé avec les propriétaires",
        contracts: "2 contrats numériques/mois",
        payment: "Paiements sécurisés (loyers, cautions)",
        advice: "Conseils personnalisés",
        assistance: "Assistance virtuelle KIA (réponses avancées)",
        contacts: "Contact avec 10 propriétaires/mois",
        searches: "20 recherches/mois avec filtres de base",
      },
    },
    {
      name: "Premium",
      price: "1 200",
      quarterly: "3 000",
      annual: "10 800",
      features: {
        properties: "Toutes les propriétés (meublées et premium)",
        chat: "Chat prioritaire avec les propriétaires",
        contracts: "Contrats illimités + paiements sécurisés",
        payment: "Paiements sécurisés avancés (échelonnement)",
        advice: "Conseils juridiques personnalisés",
        assistance: "Assistance virtuelle KIA (prioritaire)",
        contacts: "Contacts illimités avec les propriétaires",
        searches: "Recherches illimitées avec filtres avancés",
        reviews: "Avis des anciens locataires",
        virtualVisits: "Visites virtuelles (vidéo ou 3D)",
        physicalVisits: "Programmation de visites physiques",
        repairs: "Demandes de réparations via l'app",
        map: "Localisation sur carte interactive",
        forum: "Forum des locataires + chat prioritaire",
      },
    },
  ],
  proprietaire: [
    {
      name: "Gratuit",
      price: "0",
      quarterly: "0",
      annual: "0",
      features: {
        properties: "2 propriétés",
        contracts: "2 contrats de bail numériques",
        tenants: "Gestion de 2 locataires",
        chat: "Chat simple (messages prédéfinis)",
        payments: "Gestion des paiements via Mobile Money",
      },
    },
    {
      name: "Standard",
      price: "2 000",
      quarterly: "5 000",
      annual: "18 000",
      features: {
        properties: "10 propriétés",
        contracts: "Contrats personnalisables (5/mois)",
        tenants: "Gestion de 15 locataires",
        chat: "Chat avancé avec les locataires",
        payments: "Gestion des paiements (rapports mensuels)",
        storage: "Ajout de photos (500 Mo de stockage)",
        reservations: "Réception des réservations",
        stats: "Statistiques de base (revenus, occupation)",
      },
    },
    {
      name: "Premium",
      price: "5 000",
      quarterly: "12 500",
      annual: "45 000",
      features: {
        properties: "Illimité",
        contracts: "Contrats illimités avec signature numérique",
        tenants: "Gestion de locataires illimitée",
        chat: "Messagerie avancée (chat, notifications)",
        payments: "Gestion complète des paiements et locataires",
        storage: "Ajout de visites virtuelles (1 Go de stockage)",
        reservations: "Réception des réservations en temps réel",
        stats: "Statistiques détaillées (revenus, tendances)",
        ranking: "Référencement prioritaire dans les recherches",
        verification: "Vérification avancée des locataires",
        automations: "Automatisation des tâches (rappels, renouvellements)",
      },
    },
  ],
  agence: [
    {
      name: "Gratuit",
      price: "0",
      quarterly: "0",
      annual: "0",
      features: {
        properties: "2 propriétés",
        contracts: "2 contrats de bail numériques",
        tenants: "Gestion de 2 locataires",
        chat: "Chat simple (messages prédéfinis)",
        payments: "Gestion des paiements via Mobile Money",
      },
    },
    {
      name: "Standard",
      price: "6 000",
      quarterly: "15 000",
      annual: "54 000",
      features: {
        properties: "15 propriétés",
        contracts: "Génération de contrats (10/mois)",
        tenants: "Gestion de 30 locataires",
        chat: "Messagerie avancée (2 utilisateurs)",
        payments: "Gestion des paiements de loyers (rapports)",
        storage: "Ajout de photos et visites virtuelles (2 Go)",
        reservations: "Réception des réservations",
        stats: "Statistiques de base (occupation, revenus)",
        users: "Accès pour 2 agents immobiliers",
      },
    },
    {
      name: "Premium",
      price: "15 000",
      quarterly: "37 500",
      annual: "135 000",
      features: {
        properties: "Illimité",
        contracts: "Génération de contrats illimitée",
        tenants: "Gestion illimitée de locataires",
        chat: "Messagerie avancée multi-utilisateurs",
        payments: "Gestion complète et reporting avancé",
        storage: "Stockage de 15 Go (photos, vidéos)",
        reservations: "Réception des réservations en temps réel",
        stats: "Statistiques avancées (tendances, prévisions)",
        team: "Équipe illimitée (accès multi-utilisateurs)",
        advertising: "Campagne publicitaire gratuite (1 semaine/mois)",
        ranking: "Meilleur référencement + mise en avant exclusive",
        support: "Support prioritaire 24/7",
        analytics: "Rapports d'analyse du marché immobilier",
        dashboard: "Tableau de bord personnalisable",
      },
    },
  ],
};
